# Generated by Django 4.2.21 on 2025-09-24 17:33

from django.db import migrations, models
from django.utils import timezone


def populate_student_ids(apps, schema_editor):
    Student = apps.get_model('admissions', 'Student')
    year = timezone.now().year
    students = Student.objects.filter(student_id__isnull=True).order_by('id')
    counter = 1
    for student in students:
        student_id = f'STU{year}{counter:04d}'
        student.student_id = student_id
        student.save()
        counter += 1


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_student_student_id_alter_student_course'),
    ]

    operations = [
        migrations.RunPython(populate_student_ids),
    ]
