# Generated by Django 4.2.21 on 2025-09-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_auto_20250924_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
