# Generated by Django 4.2.21 on 2025-09-24 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissions', '0006_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance_pattern_score',
            field=models.FloatField(default=0.0, help_text='Attendance pattern analysis score'),
        ),
        migrations.AddField(
            model_name='student',
            name='dropout_risk_score',
            field=models.FloatField(default=0.0, help_text='AI-calculated dropout risk (0-1)'),
        ),
        migrations.AddField(
            model_name='student',
            name='performance_forecast',
            field=models.FloatField(default=0.0, help_text='Predicted final GPA'),
        ),
        migrations.AddField(
            model_name='student',
            name='recommended_career_path',
            field=models.CharField(blank=True, choices=[('Software Developer', 'Software Developer'), ('Data Scientist', 'Data Scientist'), ('Business Analyst', 'Business Analyst'), ('Engineer', 'Engineer'), ('Research Scientist', 'Research Scientist'), ('Teacher/Educator', 'Teacher/Educator'), ('Entrepreneur', 'Entrepreneur'), ('Healthcare Professional', 'Healthcare Professional'), ('Creative Professional', 'Creative Professional'), ('Management Professional', 'Management Professional')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PerformanceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_gpa', models.FloatField(default=0.0)),
                ('total_credits', models.IntegerField(default=0)),
                ('completed_subjects', models.IntegerField(default=0)),
                ('average_attendance', models.FloatField(default=0.0)),
                ('study_hours_per_week', models.IntegerField(default=0)),
                ('extracurricular_activities', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('predicted_final_gpa', models.FloatField(default=0.0)),
                ('dropout_probability', models.FloatField(default=0.0)),
                ('recommended_interventions', models.JSONField(blank=True, default=list)),
                ('career_recommendations', models.JSONField(blank=True, default=list)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='admissions.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Excused', 'Excused')], default='Present', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='admissions.student')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('student', 'date', 'subject')},
            },
        ),
    ]
