# Generated by Django 4.2.21 on 2025-09-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_student_attendance_pattern_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(default=0.0, help_text='Cumulative Grade Point Average'),
        ),
        migrations.AddField(
            model_name='student',
            name='total_credits',
            field=models.IntegerField(default=0, help_text='Total credits earned'),
        ),
    ]
