# Generated by Django 4.2.21 on 2025-09-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_student_cgpa_student_total_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.CharField(blank=True, choices=[('BTech', 'BTech'), ('BCA', 'BCA'), ('BSc', 'BSc'), ('MTech', 'MTech'), ('MCA', 'MCA'), ('MSc', 'MSc')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='institution_type',
            field=models.CharField(choices=[('School', 'School'), ('College', 'College')], default='College', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=2, null=True),
        ),
    ]
