# Generated by Django 4.2.21 on 2025-09-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_student_degree_student_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='institution_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
