# Generated by Django 4.2.21 on 2025-09-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0010_student_institution_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceanalytics',
            name='career_recommendations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='performanceanalytics',
            name='recommended_interventions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
